version: '3.8'

services:
  server:
    container_name: myapp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file: ./.env.production
    volumes:
      - ./uploads:/app/uploads
