services:
  server:
    container_name: myapp-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env.production
    volumes:
      - ./uploads:/app/uploads
    networks:
      - dokploy-network
      - cloudflared
    ports:
      - 3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.myappbackend.rule=Host(`myappbackend.kiman.site`)'
      - 'traefik.http.routers.myappbackend.entrypoints=web'
      - 'traefik.http.routers.myappbackend.service=api@internal'
      - 'traefik.http.services.myappbackend.loadbalancer.server.port=3000'

networks:
  dokploy-network:
    external: true
  cloudflared:
    external: true
