services:
  server:
    container_name: myapp-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env.production
    volumes:
      - ./uploads:/app/uploads
    networks:
      - cloudflared
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.myappbackend.rule=Host(`myappbackend.kiman.site`)'
      - 'traefik.http.routers.myappbackend.entrypoints=web'
      - 'traefik.http.routers.myappbackend.service=api@internal'
networks:
  cloudflared:
    external: true
